# Generated by Django 4.2.29 on 2026-03-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=10)),
                ('purpose', models.CharField(choices=[('register', 'Registration'), ('login', 'Login'), ('reset', 'Password Reset')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('weather_condition', models.CharField(max_length=100)),
                ('forecast_data', models.JSONField(default=dict)),
                ('farming_advisory', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('farm_size', models.FloatField(blank=True, help_text='Acres', null=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PestControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('pest_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('affected_area', models.FloatField(default=1)),
                ('symptoms', models.TextField()),
                ('recommended_pesticide', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('application_method', models.CharField(blank=True, max_length=200)),
                ('organic_alternative', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('field_area', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('crop_stage', models.CharField(max_length=100)),
                ('nitrogen_kg', models.FloatField(default=0)),
                ('phosphorus_kg', models.FloatField(default=0)),
                ('potassium_kg', models.FloatField(default=0)),
                ('recommended_fertilizer', models.TextField(blank=True)),
                ('application_schedule', models.TextField(blank=True)),
                ('estimated_cost', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('detected_disease', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('treatment_recommendation', models.TextField(blank=True)),
                ('all_predictions', models.JSONField(default=list)),
                ('model_used', models.CharField(default='rule_based', max_length=100)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('csv_file', models.FileField(upload_to='datasets/')),
                ('total_rows', models.IntegerField(default=0)),
                ('unique_labels', models.IntegerField(default=0)),
                ('label_names', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('training_log', models.TextField(blank=True)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid'), ('perennial', 'Perennial')], max_length=20)),
                ('field_area', models.FloatField()),
                ('sowing_date', models.DateField()),
                ('expected_harvest', models.DateField()),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('irrigation_method', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('feature_context', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
